# Generated by Django 6.0.2 on 2026-05-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='target',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiledata',
            name='background_picture',
            field=models.ImageField(blank=True, default='static/background_pictures/sbcf-default-backgrounds.png', null=True, upload_to='static/background_pictures/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userprofiledata',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/profile_pictures/sbcf-default-avatar.png', null=True, upload_to='static/profile_pictures/%Y/%m/%d/'),
        ),
    ]
