# Generated by Django 6.0.2 on 2026-05-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userrequest_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='target',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
    ]
