# Generated by Django 6.0.2 on 2026-07-12 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
