# Generated by Django 6.0.2 on 2026-05-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_resourceaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='can_modify_files',
            field=models.BooleanField(default=False),
        ),
    ]
