# Generated by Django 6.0.2 on 2026-05-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectrole_can_modify_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='can_execute_code',
            field=models.BooleanField(default=False),
        ),
    ]
