# Generated by Django 6.0.2 on 2026-05-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectrole_can_execute_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='can_share_file_access',
            field=models.BooleanField(default=False),
        ),
    ]
