# Generated by Django 6.0.2 on 2026-05-24 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectrole_can_share_file_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprojectrole',
            name='project',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='userprojectrole',
            name='role',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='projects.projectrole'),
        ),
        migrations.AlterField(
            model_name='userprojectrole',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
