# Generated by Django 6.0.2 on 2026-07-11 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_remove_message_msg_conv_timestamp_idx_and_more'),
        ('projects', '0020_projectrepostats_previous_branch_protection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='projects.project'),
        ),
    ]
